#!/bin/sh

# Volume
VOL="$(pacmd list-sources | grep "index:" -A7 | grep "<alsa_input.pci-0000_00_1b.0.analog-stereo>" -A6 | tail -n1 | sed 's/\s*volume: front-left: \([0-9]\+\) .*/\1/')"

while sleep 2; 
    do pacmd set-source-volume alsa_input.pci-0000_00_1b.0.analog-stereo $VOL; 
done
